import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import assert from 'node:assert/strict';
const root = resolve(import.meta.dirname, '..');
const types = readFileSync(resolve(root, 'src/features/progress/progress.types.ts'), 'utf8').replace(/^import .*\n/gm, '').replaceAll('ObjectId', 'string').replace('scheduler?: SchedulerState','scheduler: SchedulerState').replace('lapses?: number','lapses: number').replace('  card?: StudyCard;', '  card?: Pick<StudyCard, "sourceCardId" | "sourceNoteGuid" | "direction">;\n  fuzzSeed?: string;');
const source = readFileSync(resolve(root, 'src/features/progress/scheduler.ts'), 'utf8');
const seed = /  return progress\.card\?\.sourceCardId \? BigInt\(progress\.card\.sourceCardId\) : BigInt\("0x" \+ createHash\("sha256"\)\.update\(progress\.itemId\.toString\(\)\)\.digest\("hex"\)\.slice\(0, 15\)\);/;
assert.match(source, seed, 'Review the browser seed adapter when the server seed changes');
const scheduler = source.replace(/^import .*\n/gm, '').replace(seed, '  return BigInt(progress.fuzzSeed ?? progress.card?.sourceCardId ?? "0");');
const study = readFileSync(resolve(root, 'src/features/progress/studyScheduling.ts'), 'utf8').replace(/^import .*\n/gm, '');
const generated = '// Generated by the API scripts/generateBrowserScheduler.mjs. Do not edit.\n// The server supplies the SHA-256 seed; scheduling, fuzz and calendar logic are identical.\n' + types + '\n' + scheduler + '\n' + study;
const target = resolve(root, '../german-gramatic-web/src/core/generated/studyScheduler.ts');
if (process.argv.includes('--check')) { assert.equal(readFileSync(target, 'utf8'), generated, 'Regenerate the browser scheduler after model/scheduler edits'); console.log('PASS browser scheduler matches its authoritative API sources'); }
else { mkdirSync(dirname(target), { recursive: true }); writeFileSync(target, generated); console.log('Generated browser scheduler'); }
