import assert from 'node:assert/strict';
import { ObjectId } from 'mongodb';
import { DEFAULT_OPTIONS, initialScheduler, scheduleReview } from '../src/features/progress/scheduler.js';
import { withScheduler } from '../src/features/progress/reviews.js';
import { studyReviewOptions, scheduleStudyReview } from '../src/features/progress/studyScheduling.js';
import type { UserProgress } from '../src/features/progress/progress.types.js';

const now = new Date('2026-10-08T19:00:00Z');
const fresh: UserProgress = { _id: new ObjectId(), userId: new ObjectId(), itemId: new ObjectId(), itemType: 'WORD', ease: 2.5, interval: 0, repetitions: 0, lapses: 0, totalReviews: 0, isNew: false, lastReviewed: null, createdAt: new Date('2026-02-19T12:00:00Z'), nextDueDate: new Date('2026-02-28T12:00:00Z') };
fresh.scheduler = { ...initialScheduler(fresh), phase: 'REVIEW', queue: 'DAY' };
const prepared = await withScheduler(fresh);
assert.equal(prepared.scheduler?.phase, 'NEW', 'A never-reviewed zero-interval card must not acquire an overdue-review bonus');
assert.equal(prepared.isNew, true);
assert.equal(fresh.scheduler.phase, 'REVIEW', 'Read normalization must not mutate the stored snapshot');
assert.equal((await withScheduler({ ...fresh, totalReviews: undefined })).scheduler?.phase, 'NEW', 'An absent legacy counter has the same zero default as the client contract when every other history field is empty');
const options = studyReviewOptions(fresh, now);
assert.deepEqual(options.map(option => option.grade), ['AGAIN', 'HARD', 'GOOD', 'EASY']);
assert.deepEqual(options.map(option => option.phase), ['LEARNING', 'LEARNING', 'LEARNING', 'REVIEW']);
assert.equal(options[0].delaySeconds, 60);
assert.equal(options[1].delaySeconds, 330);
assert.equal(options[2].delaySeconds, 600);
assert.ok(options[3].delaySeconds <= 5 * 86400);
for (const option of options) assert.ok(Date.parse(option.nextDueDate) > +now);
assert.throws(() => scheduleStudyReview(fresh, 'REVISIT', now), /established/);
const deferred = await withScheduler({ ...fresh, nextDueDate: new Date('2026-10-13T02:00:00Z') });
assert.equal(deferred.scheduler?.phase, 'NEW');
assert.equal(+deferred.buriedUntil!, +deferred.nextDueDate, 'Restoring NEW must retain a manual future deferral');
const old = { ...fresh, interval: 1, repetitions: 1, totalReviews: undefined, ease: 2.36, lastReviewed: new Date('2026-02-27T07:09:17Z'), scheduler: { ...fresh.scheduler, interval: 1, ease: 2.36, options: { ...DEFAULT_OPTIONS, learningSteps: [10, 720], relearningSteps: [1440], graduatingGood: 3, graduatingEasy: 5 } } };
assert.equal((await withScheduler(old)).scheduler?.phase, 'REVIEW', 'Nonzero stored history requires an explicit repair, not an automatic reset');
assert.ok(studyReviewOptions(old, now).find(option => option.grade === 'GOOD')!.delaySeconds > 200 * 86400, 'The Anki overdue bonus applies to a retained historical schedule');
for (const grade of ['AGAIN', 'HARD', 'GOOD', 'EASY'] as const) assert.ok(+scheduleReview(old, grade, now).nextDueDate > +now);
for (const history of [{ totalReviews: 1 }, { repetitions: 1 }, { lastReviewed: now }, { interval: 1 }, { lapses: 1 }]) assert.equal((await withScheduler({ ...fresh, ...history })).scheduler?.phase, 'REVIEW');
for (const history of [{ interval: 1 }, { lapses: 1 }]) assert.equal((await withScheduler({ ...fresh, scheduler: { ...fresh.scheduler, ...history } })).scheduler?.phase, 'REVIEW', 'Nonzero scheduler evidence also prevents an automatic reset');
console.log('PASS unstudied-state recovery, short initial steps, manual deferrals, retained historical reviews and future rating dates');
