import assert from "node:assert/strict";
import { mkdtemp, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { ObjectId } from "mongodb";
import { WORD_CARD_PROMPT_VERSION, WORD_CARD_REVIEW_INSTRUCTIONS, WORD_CARD_REVIEW_SCHEMA } from "./lib/wordCardPrompt.js";
import { ANSWER_REVIEW_MODEL, ANSWER_REVIEW_PROMPT_HASH, answerReviewGroupId, answerReviewSHA256, buildAnswerReviewInputs, retainedGermanConstructionMatches, validateAnswerReviewCheckpoint, validateAnswerReviewDecisions, writeAnswerReviewPrivate } from "./reviewWordCardAnswers.js";

const hex = (number: number) => number.toString(16).padStart(24, "0"), oid = (number: number) => new ObjectId(hex(number));
const variant = { german: "Das Auto", category: "NOUN", forms: { gender: "das", plural: "Die Autos" }, notes: "Die Autos", examples: ["Das Auto ist neu.", "Ich fahre mit dem Auto."], confidence: "high", reviewReason: "" };
const translation = { relationId: hex(3), spanish: "el coche", examples: ["El coche es nuevo.", "Voy en coche."], variant };
const review = { version: 1, stage: "independent_review", promptVersion: WORD_CARD_PROMPT_VERSION, promptHash: answerReviewSHA256(WORD_CARD_PROMPT_VERSION + WORD_CARD_REVIEW_INSTRUCTIONS + JSON.stringify(WORD_CARD_REVIEW_SCHEMA)), sourceHash: "a".repeat(64), offset: 0, selected: 1, completed: 1, pending: 0, entries: [{ id: hex(1), translations: [translation], confidence: "high", studyEligible: true }] };
const recognition = { itemType: "WORD", relationId: oid(3), card: { direction: "DE_ES", prompt: "Das Auto", answer: "el coche", acceptedAnswers: ["el coche", "el automóvil", "el coche / el barco"] }, userId: "private-owner", _id: "private-progress", scheduler: { phase: "REVIEW" }, sourceNoteGuid: "private-guid" };
const production = { ...recognition, card: { direction: "ES_DE", prompt: "el coche", answer: "Das Auto", acceptedAnswers: ["Das Auto", "Der Auto", "Auto"] } };
const snapshot = { collections: { WORDS_DE: [{ _id: oid(1), word: "Auto" }], WORDS_ES: [{ _id: oid(2), word: "coche" }], WORDS_ES_DE: [{ _id: oid(3), main: oid(2), translated: oid(1) }], userprogresses: [recognition, { ...recognition, userId: "private-second-owner", _id: "private-second-progress" }, production] } };
const prepared = buildAnswerReviewInputs(snapshot, review);
assert.equal(prepared.inputs.length, 2, "Duplicate owners with the same relation/direction/original list share one review group");
assert.equal(prepared.coverage.multipleAnswerCards, 3);
assert.ok(!JSON.stringify(prepared).includes("private-"));
const deEs = prepared.inputs.find(input => input.direction === "DE_ES")!, esDe = prepared.inputs.find(input => input.direction === "ES_DE")!;
assert.equal(deEs.canonical.spanish, "el coche"); assert.equal(esDe.canonical.german, "Das Auto");
assert.equal(deEs.id, answerReviewGroupId(hex(3), "DE_ES", recognition.card.acceptedAnswers));
assert.throws(() => buildAnswerReviewInputs(snapshot, { ...review, completed: 0, pending: 1 }), /Complete current/);
assert.throws(() => buildAnswerReviewInputs(snapshot, { ...review, entries: [{ ...review.entries[0], id: hex(99) }] }), /exact German/);
const excluded = buildAnswerReviewInputs(snapshot, { ...review, entries: [{ ...review.entries[0], confidence: "needs_review" }] });
assert.equal(excluded.inputs.length, 0); assert.equal(excluded.excludedGroups.length, 2);
const decisions = prepared.inputs.map(input => ({ id: input.id, retainedAnswers: input.direction === "DE_ES" ? ["el coche", "el automóvil"] : ["Das Auto"], reason: "Correct same-sense choices retained; slash-conflated or wrong noun articles dropped", confidence: "high", reviewReason: "" }));
assert.equal(validateAnswerReviewDecisions({ entries: decisions }, prepared.inputs).length, 2);
assert.throws(() => validateAnswerReviewDecisions({ entries: [] }, prepared.inputs), /every exact/);
assert.throws(() => validateAnswerReviewDecisions({ entries: [{ ...decisions[0], id: hex(999) }, decisions[1]] }, prepared.inputs), /identity/);
assert.throws(() => validateAnswerReviewDecisions({ entries: [{ ...decisions[0], retainedAnswers: ["invented synonym"] }, decisions[1]] }, prepared.inputs), /exact valid original/);
assert.throws(() => validateAnswerReviewDecisions({ entries: [{ ...decisions[0], id: decisions[1].id }, decisions[1]] }, prepared.inputs), /identity/);
assert.throws(() => validateAnswerReviewDecisions({ entries: [{ id: deEs.id, retainedAnswers: ["el coche / el barco"], reason: "bad", confidence: "high", reviewReason: "" }] }, [deEs]), /exact valid original/);
assert.throws(() => validateAnswerReviewDecisions({ entries: [{ id: esDe.id, retainedAnswers: ["Der Auto"], reason: "bad", confidence: "high", reviewReason: "" }] }, [esDe]), /construction identity/);
assert.throws(() => validateAnswerReviewDecisions({ entries: [{ id: esDe.id, retainedAnswers: ["Auto"], reason: "bad", confidence: "high", reviewReason: "" }] }, [esDe]), /construction identity/);
assert.equal(retainedGermanConstructionMatches("helfen", { ...esDe.canonical, german: "jemandem helfen", category: "VERB" }), false);
assert.equal(retainedGermanConstructionMatches("jemanden helfen", { ...esDe.canonical, german: "jemandem helfen", category: "VERB" }), false);
assert.equal(retainedGermanConstructionMatches("etwas vorstellen", { ...esDe.canonical, german: "sich etwas vorstellen", category: "VERB" }), false);
assert.equal(retainedGermanConstructionMatches("vorbeugen", { ...esDe.canonical, german: "einer Krankheit vorbeugen", category: "VERB" }), false, "An article-bearing dative complement cannot disappear merely because no jemand/etwas slot exists");
assert.equal(retainedGermanConstructionMatches("mit jemandem verhandeln", { ...esDe.canonical, german: "mit jemandem über den Preis verhandeln", category: "VERB" }), false, "Matching jemand slots do not permit loss of a fixed prepositional complement");
assert.equal(retainedGermanConstructionMatches("für jemandem über den Preis verhandeln", { ...esDe.canonical, german: "mit jemandem über den Preis verhandeln", category: "VERB" }), false);
assert.equal(retainedGermanConstructionMatches("über den Preis mit jemandem verhandeln", { ...esDe.canonical, german: "mit jemandem über den Preis verhandeln", category: "VERB" }), false, "The canonical production front preserves complement order");
assert.equal(retainedGermanConstructionMatches("  Einer   Krankheit vorbeugen!  ", { ...esDe.canonical, german: "einer Krankheit vorbeugen", category: "VERB" }), true, "Case, spacing and terminal punctuation variants preserve the full construction");
assert.equal(retainedGermanConstructionMatches("Der Ka\u0308fer", { ...esDe.canonical, german: "Der Käfer", category: "NOUN", forms: { gender: "der" } }), true, "Equivalent Unicode spellings preserve the German lexical front");
const annotated = { ...deEs, originalAcceptedAnswers: ["conversar (rflxv.)", "conversar", "<b>conversar</b>"] };
assert.throws(() => validateAnswerReviewDecisions({ entries: [{ id: annotated.id, retainedAnswers: ["conversar (rflxv.)"], reason: "bad", confidence: "high", reviewReason: "" }] }, [annotated]), /exact valid original/);
assert.throws(() => validateAnswerReviewDecisions({ entries: [{ id: annotated.id, retainedAnswers: ["<b>conversar<\/b>"], reason: "bad", confidence: "high", reviewReason: "" }] }, [annotated]), /exact valid original/);
const binding = { sourceHash: "a".repeat(64), reviewHash: "b".repeat(64), inputsHash: "c".repeat(64) }, input = prepared.inputs[0];
const checkpoint = { ...binding, model: ANSWER_REVIEW_MODEL, promptHash: ANSWER_REVIEW_PROMPT_HASH, inputHash: answerReviewSHA256(JSON.stringify(input)), completedAt: new Date().toISOString(), entry: decisions[0] };
assert.equal(validateAnswerReviewCheckpoint(checkpoint, input, binding).id, input.id);
assert.throws(() => validateAnswerReviewCheckpoint({ ...checkpoint, model: "old-model" }, input, binding), /provenance/);
assert.throws(() => validateAnswerReviewCheckpoint(checkpoint, { ...input, originalAcceptedAnswers: ["changed"] }, binding), /provenance/);
assert.throws(() => validateAnswerReviewCheckpoint(checkpoint, input, { ...binding, sourceHash: "d".repeat(64) }), /provenance/);
const directory = await mkdtemp(join(tmpdir(), "word-answer-review-"));
try { const path = join(directory, "private", "answer.json"); await writeAnswerReviewPrivate(path, JSON.stringify(checkpoint)); assert.equal((await stat(path)).mode & 0o777, 0o600); assert.equal((await stat(join(directory, "private"))).mode & 0o777, 0o700); }
finally { await rm(directory, { recursive: true, force: true }); }
console.log("Answer-review subset, sense/direction input, required-construction guards, deduplication, provenance/resume and private-file tests passed. No provider/database calls.");
