import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { ingestAgentWordCards, reconsiderAgentWordCards, strictAgentSchema, validateAgentJob } from "./agentWordCardAudit.js";
import { WORD_CARD_AUDIT_INSTRUCTIONS, WORD_CARD_AUDIT_SCHEMA, WORD_CARD_FORM_KEYS, WORD_CARD_PROMPT_VERSION, WORD_CARD_REVIEW_INSTRUCTIONS, WORD_CARD_REVIEW_SCHEMA, validateWordCardDrafts, type AuditWordInput, type WordCardDraft } from "./lib/wordCardPrompt.js";

const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const sourceHash = hash("controlled-source");
const input: AuditWordInput = { id: "000000000000000000000001", german: { word: "Haus", categories: ["NOUN"], forms: { gender: "das" }, notes: "", examples: [] }, translations: [{ relationId: "000000000000000000000003", spanish: { id: "000000000000000000000002", word: "la casa", examples: [] } }], distinctLiveCards: [] };
const draft: WordCardDraft = { id: input.id, german: "Das Haus", category: "NOUN", forms: { ...Object.fromEntries(WORD_CARD_FORM_KEYS.map(key => [key, ""])), gender: "das", plural: "Die Häuser" } as WordCardDraft["forms"], notes: "Die Häuser", examples: ["Das Haus ist alt.", "Ich kaufe ein Haus."], translations: [{ relationId: input.translations[0].relationId, spanish: "la casa", examples: ["La casa es vieja.", "Compro una casa."] }], issues: [], confidence: "high", reviewReason: "", studyEligible: true, relatedCandidates: [] };
const directory = await mkdtemp(join(tmpdir(), "word-agent-checkpoint-"));
const provenance = { agent: "/root/word_prompt_research", effort: "xhigh", jobSHA256: hash("job"), resultSHA256: hash("result") };
try {
  const controlled: Parameters<typeof validateAgentJob>[1] = { sourceHash, inputs: [input], firstPass: new Map(), stage: "draft", stagePromptHash: hash(WORD_CARD_PROMPT_VERSION + WORD_CARD_AUDIT_INSTRUCTIONS + JSON.stringify(WORD_CARD_AUDIT_SCHEMA)), directory };
  const job = { version: 1, execution: "codex-agent", stage: "draft", sourceHash, promptVersion: WORD_CARD_PROMPT_VERSION, promptHash: controlled.stagePromptHash, model: "gpt-6.1-sol", instructions: WORD_CARD_AUDIT_INSTRUCTIONS, schema: WORD_CARD_AUDIT_SCHEMA, entries: [input] };
  assert.deepEqual(validateAgentJob(job, controlled), [input]);
  assert.throws(() => validateAgentJob({ ...job, entries: [{ ...input, german: { ...input.german, word: "changed" } }] }, controlled), /changed/u);
  assert.throws(() => strictAgentSchema({ entries: [{ ...draft, owner: "unexpected" }] }, WORD_CARD_AUDIT_SCHEMA), /exact schema/u);
  assert.throws(() => strictAgentSchema({ entries: [{ ...draft, confidence: "guessed" }] }, WORD_CARD_AUDIT_SCHEMA), /schema value/u);
  await assert.rejects(ingestAgentWordCards(job, { entries: [draft] }, controlled, { ...provenance, effort: "low" }), /high\/xhigh/u);
  const invalid = await ingestAgentWordCards(job, { entries: [{ ...draft, notes: "Die Häuser<br>" }] }, controlled, provenance);
  assert.equal(invalid.accepted, 0); assert.deepEqual(invalid.remainingIds, [input.id]);
  assert.ok(validateWordCardDrafts({ entries: [{ ...draft, german: "das Haus" }] }, [input]).some(error => error.includes("initial article")));
  const verb = { ...draft, category: "VERB", german: "einer Krankheit vorbeugen", forms: { ...draft.forms, gender: "", plural: "", perfect: "hat vorgebeugt", past: "ich beugte vor", imperativ: "beug vor!, beugt vor!" }, notes: "hat vorgebeugt\nich beugte vor\nbeug vor!, beugt vor!" };
  assert.ok(validateWordCardDrafts({ entries: [verb] }, [input]).some(error => error.includes("initial article")));
  assert.ok(!validateWordCardDrafts({ entries: [{ ...verb, german: "Einer Krankheit vorbeugen" }] }, [input]).some(error => error.includes("initial article")));
  assert.ok(!validateWordCardDrafts({ entries: [{ ...verb, german: "in die Schule gehen" }] }, [input]).some(error => error.includes("initial article")), "Articles inside constructions retain normal lowercase");
  assert.ok(validateWordCardDrafts({ entries: [{ ...draft, examples: ["Das Haus ist alt", draft.examples[1]] }] }, [input]).some(error => error.includes("final punctuation")));
  const lowerSpanish = { ...draft, translations: [{ ...draft.translations[0], examples: ["la casa es vieja.", "Compro una casa."] }] };
  assert.ok(validateWordCardDrafts({ entries: [lowerSpanish] }, [input]).some(error => error.includes("start uppercase")));
  const quoted = { ...draft, examples: ["Sie sagte: „Läuft!“", "Ist das Haus alt?"], translations: [{ ...draft.translations[0], examples: ["Dijo: «¡Todo va bien!»", "¿Es vieja la casa?"] }] };
  assert.deepEqual(validateWordCardDrafts({ entries: [quoted] }, [input]), [], "Question and quotation punctuation stays inside the rendered translation parentheses");
  const ranked = { ...draft, german: "hochrangig", category: "ADJECTIVE", forms: Object.fromEntries(WORD_CARD_FORM_KEYS.map(key => [key, ""])) as WordCardDraft["forms"], notes: "Komparativ: höherrangig, höchstrangig", examples: ["Ein hochrangiger Beamter kommt.", "Sie empfängt hochrangige Gäste."], translations: [{ ...draft.translations[0], spanish: "de alto rango", examples: ["Llega un funcionario de alto rango.", "Recibe a invitados de alto rango."] }] };
  assert.deepEqual(validateWordCardDrafts({ entries: [ranked] }, [input]), [], "The independently source-checked compound retains actual first-element comparison forms");
  for (const unrelated of [{ ...ranked, german: "wichtig" }, { ...ranked, category: "ADVERB" }, { ...ranked, notes: "Komparativ: höherrangig, höchstrangiger" }]) {
    assert.ok(validateWordCardDrafts({ entries: [unrelated] }, [input]).some(error => error.includes("annotation outside allowed convention")), "The non-am exception cannot admit another word, category or invented degree");
  }
  const result = await ingestAgentWordCards(job, { entries: [draft] }, controlled, provenance);
  assert.equal(result.status, "agent_batch_checkpointed");
  const savedPath = join(directory, "entries", `${input.id}.json`), saved = JSON.parse(await readFile(savedPath, "utf8"));
  assert.equal(saved.inputHash, hash(JSON.stringify(input))); assert.equal(saved.execution.agent, provenance.agent); assert.equal(saved.execution.kind, "codex-agent");
  assert.equal((await stat(savedPath)).mode & 0o777, 0o600);
  const firstSaved = await readFile(savedPath, "utf8");
  await ingestAgentWordCards(job, { entries: [{ ...draft, issues: ["later attempt"] }] }, controlled, provenance);
  assert.equal(await readFile(savedPath, "utf8"), firstSaved, "Validated completed checkpoints are never silently replaced");
  const variant = { german: draft.german, category: draft.category, forms: draft.forms, notes: draft.notes, examples: draft.examples, confidence: draft.confidence, reviewReason: draft.reviewReason };
  const reviewed = { ...draft, translations: [{ ...draft.translations[0], variant }] };
  const reviewContext: Parameters<typeof validateAgentJob>[1] = { ...controlled, stage: "independent_review", stagePromptHash: hash(WORD_CARD_PROMPT_VERSION + WORD_CARD_REVIEW_INSTRUCTIONS + JSON.stringify(WORD_CARD_REVIEW_SCHEMA)), directory: join(directory, "review"), firstPass: new Map([[input.id, saved]]) };
  const reviewJob = { ...job, stage: "independent_review", promptHash: reviewContext.stagePromptHash, instructions: WORD_CARD_REVIEW_INSTRUCTIONS, schema: WORD_CARD_REVIEW_SCHEMA, entries: [{ ...input, draft }] };
  await assert.rejects(ingestAgentWordCards(reviewJob, { entries: [reviewed] }, reviewContext, provenance), /different actual agent/u);
  const second = await ingestAgentWordCards(reviewJob, { entries: [reviewed] }, reviewContext, { ...provenance, agent: "/root/word_semantic_audit" });
  assert.equal(second.accepted, 1);
  const reviewSaved = JSON.parse(await readFile(join(reviewContext.directory, "entries", `${input.id}.json`), "utf8"));
  assert.equal(reviewSaved.inputHash, hash(JSON.stringify({ entry: input, draft })));
  assert.throws(() => validateAgentJob(reviewJob, { ...reviewContext, firstPass: new Map([[input.id, { ...saved, draft: { ...draft, german: "Das Gebäude" } }]]) }), /changed/u);
  assert.ok(!JSON.stringify(job).includes("userId"), "Provider-independent lexical jobs contain no owner identities");
  const reviewPath = join(reviewContext.directory, "entries", `${input.id}.json`), priorBytes = await readFile(reviewPath, "utf8"), evidencePath = join(directory, "evidence.json"), planPath = join(directory, "reconsideration-plan.json");
  const evidenceBytes = JSON.stringify({ sourceHash, id: input.id, checkedAspect: "countable dwelling plural" });
  const policy = "Use real same-sense forms and preserve independently reviewed prior content";
  await writeFile(evidencePath, evidenceBytes, { mode: 0o600 });
  const finalReviewPath = join(directory, "final-review.json");
  const planBytes = JSON.stringify({ stage: "planned_final_lexical_reconsideration", sourceHash, formPolicy: policy, entries: [{ id: input.id }], sourceCheckFiles: [evidencePath], finalReviewPath });
  await writeFile(planPath, planBytes, { mode: 0o600 });
  const reconsiderJob = { ...reviewJob, reconsideration: { version: 1, planPath, planSHA256: hash(planBytes), policy, sourceChecks: [{ path: evidencePath, sha256: hash(evidenceBytes) }], priorCheckpoints: [{ id: input.id, sha256: hash(priorBytes) }] } };
  const finalReviewer = { ...provenance, agent: "/root/word_audit_migration", jobSHA256: hash(JSON.stringify(reconsiderJob)), resultSHA256: hash("final-result") };
  const finalResult = { entries: [{ ...reviewed, issues: ["Independently reconsidered against recorded countable sense evidence"] }] };
  await assert.rejects(reconsiderAgentWordCards(reconsiderJob, finalResult, reviewContext, provenance), /both earlier authors/u);
  await assert.rejects(reconsiderAgentWordCards(reconsiderJob, finalResult, reviewContext, { ...finalReviewer, agent: "/root/word_semantic_audit" }), /both earlier authors/u);
  await assert.rejects(reconsiderAgentWordCards(reconsiderJob, { entries: [{ ...reviewed, notes: "Die Häuser<br>" }] }, reviewContext, finalReviewer), /before reopening/u);
  await assert.rejects(reconsiderAgentWordCards({ ...reconsiderJob, reconsideration: { ...reconsiderJob.reconsideration, planSHA256: hash("stale-plan") } }, finalResult, reviewContext, finalReviewer), /exact explicit source-bound plan/u);
  await writeFile(evidencePath, "changed evidence", { mode: 0o600 });
  await assert.rejects(reconsiderAgentWordCards(reconsiderJob, finalResult, reviewContext, finalReviewer), /evidence.*changed/u);
  await writeFile(evidencePath, evidenceBytes, { mode: 0o600 });
  await writeFile(finalReviewPath, "frozen aggregate", { mode: 0o600 });
  await assert.rejects(reconsiderAgentWordCards(reconsiderJob, finalResult, reviewContext, finalReviewer), /already frozen/u);
  await rm(finalReviewPath);
  assert.equal(await readFile(reviewPath, "utf8"), priorBytes, "All refusal paths preserve the valid earlier review exactly");
  const reconsidered = await reconsiderAgentWordCards(reconsiderJob, finalResult, reviewContext, finalReviewer);
  assert.equal(reconsidered.status, "agent_reconsideration_checkpointed"); assert.equal(reconsidered.priorReviewsPreserved, 1);
  const historyPath = join(reviewContext.directory, "reconsideration-history", input.id, `${hash(priorBytes)}.json`);
  assert.equal(await readFile(historyPath, "utf8"), priorBytes, "The complete previous review is preserved byte for byte under its checksum");
  assert.equal((await stat(historyPath)).mode & 0o777, 0o600);
  assert.equal(JSON.parse(await readFile(reviewPath, "utf8")).execution.agent, finalReviewer.agent);
  assert.deepEqual(JSON.parse(await readFile(reviewPath, "utf8")).draft.issues, finalResult.entries[0].issues);
  const finalBytes = await readFile(reviewPath, "utf8");
  await assert.rejects(reconsiderAgentWordCards(reconsiderJob, finalResult, reviewContext, finalReviewer), /stale or invalid/u);
  assert.equal(await readFile(reviewPath, "utf8"), finalBytes, "A stale prior-review binding cannot replace the final result again");
  console.log("PASS exact lexical job binding, strict schema/plain text, private checkpoint preservation and separate-agent review");
  console.log("PASS explicit source-bound final reconsideration, distinct third reviewer, refusal preservation and exact private history");
} finally { await rm(directory, { recursive: true, force: true }); }
